In [3]:
!pip install streamlit plotly -q

In [4]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

print("Libraries imported successfully!")

Libraries imported successfully!

In [6]:
from google.colab import files

uploaded = files.upload()

Saving CII_Master_Match_Level_Dataset.csv to CII_Master_Match_Level_Dataset (2).csv

In [7]:
df = pd.read_csv("CII_Master_Match_Level_Dataset (2).csv")

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully!
Rows: 474
Columns: 24

In [8]:
print("Columns in the dataset:")
print(df.columns.tolist())

print("\nSelected captains:")
print(df["Captain"].unique())

Columns in the dataset:
['Match_ID', 'Date', 'Year', 'India', 'Opponent', 'Venue', 'City', 'Toss_Winner', 'Toss_Decision', 'Match_Winner', 'India_Result', 'Season', 'Match_Type', 'Location_Type', 'Captain', 'Event_Name', 'Match_Number', 'Pressure_Match', 'Win_Score', 'Pressure_Score', 'Overseas_Score', 'Toss_Decision_Score', 'Home_Performance_Score', 'CII']

Selected captains:
['Sourav Ganguly' 'Rahul Dravid' 'Virender Sehwag' 'MS Dhoni'
 'Suresh Raina' 'Virat Kohli' 'Ajinkya Rahane' 'Rohit Sharma'
 'Shikhar Dhawan' 'KL Rahul' 'Shubman Gill']

In [9]:
selected_captains = [
    "Sourav Ganguly",
    "Rahul Dravid",
    "MS Dhoni",
    "Virat Kohli",
    "Rohit Sharma"
]

dashboard_df = df[df["Captain"].isin(selected_captains)].copy()

print("Dashboard dataset created successfully!")
print("Total matches:", len(dashboard_df))
print("\nCaptains:")
print(dashboard_df["Captain"].value_counts())

Dashboard dataset created successfully!
Total matches: 422

Captains:
Captain
MS Dhoni          223
Virat Kohli        87
Rahul Dravid       57
Rohit Sharma       47
Sourav Ganguly      8
Name: count, dtype: int64

In [10]:
cii_summary = (
    dashboard_df[
        [
            "Captain",
            "Win_Score",
            "Pressure_Score",
            "Overseas_Score",
            "Toss_Decision_Score",
            "Home_Performance_Score",
            "CII"
        ]
    ]
    .drop_duplicates("Captain")
    .sort_values("CII", ascending=False)
    .reset_index(drop=True)
)

cii_summary

,Captain,Win_Score,Pressure_Score,Overseas_Score,Toss_Decision_Score,Home_Performance_Score,CII
0,Rohit Sharma,84.44,92.00,80.95,85.00,87.50,86.18
1,Virat Kohli,69.05,69.23,71.15,72.97,65.62,69.59
2,MS Dhoni,62.02,77.14,58.06,60.91,67.86,65.72
3,Rahul Dravid,55.56,33.33,50.00,55.56,68.75,50.87
4,Sourav Ganguly,50.00,NaN,75.00,40.00,25.00,49.67

In [12]:
fig = px.bar(
    cii_summary,
    x="Captain",
    y="CII",
    title="Captain Impact Index (CII) Comparison",
    text="CII",
    labels={
        "Captain": "Captain",
        "CII": "CII Score"
    }
)

fig.update_traces(
    texttemplate="%{text:.2f}",
    textposition="outside"
)

fig.update_layout(
    yaxis_range=[0, 100],
    height=500
)

fig.show()

In [13]:
criteria_df = cii_summary[
    [
        "Captain",
        "Win_Score",
        "Pressure_Score",
        "Overseas_Score",
        "Toss_Decision_Score",
        "Home_Performance_Score"
    ]
].copy()

criteria_df

,Captain,Win_Score,Pressure_Score,Overseas_Score,Toss_Decision_Score,Home_Performance_Score
0,Rohit Sharma,84.44,92.00,80.95,85.00,87.50
1,Virat Kohli,69.05,69.23,71.15,72.97,65.62
2,MS Dhoni,62.02,77.14,58.06,60.91,67.86
3,Rahul Dravid,55.56,33.33,50.00,55.56,68.75
4,Sourav Ganguly,50.00,NaN,75.00,40.00,25.00

In [14]:
criteria_long = criteria_df.melt(
    id_vars="Captain",
    var_name="Criteria",
    value_name="Score"
)

criteria_long["Criteria"] = criteria_long["Criteria"].replace({
    "Win_Score": "Win Score",
    "Pressure_Score": "Pressure Score",
    "Overseas_Score": "Overseas Score",
    "Toss_Decision_Score": "Toss Decision Score",
    "Home_Performance_Score": "Home Performance Score"
})

fig = px.bar(
    criteria_long,
    x="Criteria",
    y="Score",
    color="Captain",
    barmode="group",
    title="CII Criteria Comparison",
    text="Score"
)

fig.update_traces(
    texttemplate="%{text:.1f}",
    textposition="outside"
)

fig.update_layout(
    yaxis_range=[0, 100],
    height=600,
    xaxis_title="Performance Criteria",
    yaxis_title="Score"
)

fig.show()

In [15]:
%%writefile cii_dashboard.py

import streamlit as st
import pandas as pd
import plotly.express as px

# Page configuration
st.set_page_config(
    page_title="Captain Impact Index",
    page_icon="🏏",
    layout="wide"
)

# Title
st.title("🏏 Captain Impact Index (CII)")
st.subheader("Indian Men's ODI Captains — 2005 to 2025")

# Load dataset
df = pd.read_csv("CII_Master_Match_Level_Dataset.csv")

# Selected captains
selected_captains = [
    "Sourav Ganguly",
    "Rahul Dravid",
    "MS Dhoni",
    "Virat Kohli",
    "Rohit Sharma"
]

dashboard_df = df[df["Captain"].isin(selected_captains)].copy()

st.success("CII Dashboard loaded successfully!")

Writing cii_dashboard.py

In [16]:
import shutil

shutil.copy(
    "CII_Master_Match_Level_Dataset (2).csv",
    "CII_Master_Match_Level_Dataset.csv"
)

print("Dataset copied successfully!")

Dataset copied successfully!

In [17]:
!streamlit run cii_dashboard.py &>/content/streamlit.log &

import time
time.sleep(3)

!cat /content/streamlit.log

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

2026-10-03 09:46:52.943 Uvicorn server started on :::8501

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.23.235.85:8501

In [19]:
from google.colab import output

dashboard_url = output.eval_js(
    "google.colab.kernel.proxyPort(8501)"
)

print("CII Dashboard URL:")
print(dashboard_url)

CII Dashboard URL:
https://8501-m-s-kkb-use1b2-2isdo80vtbpcs-b.us-east1-2.prod.colab.dev

In [20]:
!cat /content/streamlit.log

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

2026-10-03 09:46:52.943 Uvicorn server started on :::8501

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.23.235.85:8501

2026-10-03 09:50:48.187 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-use1b2-2isdo80vtbpcs-b.us-east1-2.prod.colab.dev, host=m-s-kkb-use1b2-2isdo80vtbpcs.us-east1-b.c.codatalab-user-runtimes.internal:8007
2026-10-03 09:50:50.544 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-use1b2-2isdo80vtbpcs-b.us-east1-2.prod.colab.dev, host=m-s-kkb-use1b2-2isdo80vtbpcs.us-east1-b.c.codatalab-user-runtimes.internal:8007
2026-10-03 09:50:58.769 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-use1b2-2isdo80vtbpcs-b.us-east1-2.prod.colab.dev, host=m-s-kkb-use1b2-2isdo80vtbpcs.us-east1-b.c.codatalab-user-runtimes.internal:8007
2026-10-03 09:51:02.755 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-use1b2-2isdo80vtbpcs-b.us-east1-2.prod.colab.dev, host=m-s-kkb-use1b2-2isdo80vtbpcs.us-east1-b.c.codatalab-user-runtimes.internal:8007
2026-10-03 09:51:08.709 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-use1b2-2isdo80vtbpcs-b.us-east1-2.prod.colab.dev, host=m-s-kkb-use1b2-2isdo80vtbpcs.us-east1-b.c.codatalab-user-runtimes.internal:8007
2026-10-03 09:51:14.419 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-use1b2-2isdo80vtbpcs-b.us-east1-2.prod.colab.dev, host=m-s-kkb-use1b2-2isdo80vtbpcs.us-east1-b.c.codatalab-user-runtimes.internal:8007
2026-10-03 09:51:18.807 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-use1b2-2isdo80vtbpcs-b.us-east1-2.prod.colab.dev, host=m-s-kkb-use1b2-2isdo80vtbpcs.us-east1-b.c.codatalab-user-runtimes.internal:8007
2026-10-03 09:51:23.228 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-use1b2-2isdo80vtbpcs-b.us-east1-2.prod.colab.dev, host=m-s-kkb-use1b2-2isdo80vtbpcs.us-east1-b.c.codatalab-user-runtimes.internal:8007
2026-10-03 09:51:28.175 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-use1b2-2isdo80vtbpcs-b.us-east1-2.prod.colab.dev, host=m-s-kkb-use1b2-2isdo80vtbpcs.us-east1-b.c.codatalab-user-runtimes.internal:8007
2026-10-03 09:51:32.594 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-use1b2-2isdo80vtbpcs-b.us-east1-2.prod.colab.dev, host=m-s-kkb-use1b2-2isdo80vtbpcs.us-east1-b.c.codatalab-user-runtimes.internal:8007
2026-10-03 09:51:37.550 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-use1b2-2isdo80vtbpcs-b.us-east1-2.prod.colab.dev, host=m-s-kkb-use1b2-2isdo80vtbpcs.us-east1-b.c.codatalab-user-runtimes.internal:8007
2026-10-03 09:51:42.668 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-use1b2-2isdo80vtbpcs-b.us-east1-2.prod.colab.dev, host=m-s-kkb-use1b2-2isdo80vtbpcs.us-east1-b.c.codatalab-user-runtimes.internal:8007
2026-10-03 09:51:47.488 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-use1b2-2isdo80vtbpcs-b.us-east1-2.prod.colab.dev, host=m-s-kkb-use1b2-2isdo80vtbpcs.us-east1-b.c.codatalab-user-runtimes.internal:8007
2026-10-03 09:51:52.555 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-use1b2-2isdo80vtbpcs-b.us-east1-2.prod.colab.dev, host=m-s-kkb-use1b2-2isdo80vtbpcs.us-east1-b.c.codatalab-user-runtimes.internal:8007
2026-10-03 09:51:57.245 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-use1b2-2isdo80vtbpcs-b.us-east1-2.prod.colab.dev, host=m-s-kkb-use1b2-2isdo80vtbpcs.us-east1-b.c.codatalab-user-runtimes.internal:8007
2026-10-03 09:52:02.634 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-use1b2-2isdo80vtbpcs-b.us-east1-2.prod.colab.dev, host=m-s-kkb-use1b2-2isdo80vtbpcs.us-east1-b.c.codatalab-user-runtimes.internal:8007
2026-10-03 09:52:13.528 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-use1b2-2isdo80vtbpcs-b.us-east1-2.prod.colab.dev, host=m-s-kkb-use1b2-2isdo80vtbpcs.us-east1-b.c.codatalab-user-runtimes.internal:8007
2026-10-03 09:52:19.069 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-use1b2-2isdo80vtbpcs-b.us-east1-2.prod.colab.dev, host=m-s-kkb-use1b2-2isdo80vtbpcs.us-east1-b.c.codatalab-user-runtimes.internal:8007
2026-10-03 09:52:26.996 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-use1b2-2isdo80vtbpcs-b.us-east1-2.prod.colab.dev, host=m-s-kkb-use1b2-2isdo80vtbpcs.us-east1-b.c.codatalab-user-runtimes.internal:8007
2026-10-03 09:52:31.716 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-use1b2-2isdo80vtbpcs-b.us-east1-2.prod.colab.dev, host=m-s-kkb-use1b2-2isdo80vtbpcs.us-east1-b.c.codatalab-user-runtimes.internal:8007
2026-10-03 09:52:35.660 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-use1b2-2isdo80vtbpcs-b.us-east1-2.prod.colab.dev, host=m-s-kkb-use1b2-2isdo80vtbpcs.us-east1-b.c.codatalab-user-runtimes.internal:8007
2026-10-03 09:52:40.798 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-use1b2-2isdo80vtbpcs-b.us-east1-2.prod.colab.dev, host=m-s-kkb-use1b2-2isdo80vtbpcs.us-east1-b.c.codatalab-user-runtimes.internal:8007
2026-10-03 09:52:44.930 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-use1b2-2isdo80vtbpcs-b.us-east1-2.prod.colab.dev, host=m-s-kkb-use1b2-2isdo80vtbpcs.us-east1-b.c.codatalab-user-runtimes.internal:8007

In [21]:
!pkill -f "streamlit run cii_dashboard.py" || true

print("Old Streamlit server stopped.")

^C
Old Streamlit server stopped.

In [22]:
!streamlit run cii_dashboard.py \
    --server.address=0.0.0.0 \
    --server.port=8501 \
    --server.enableCORS=false \
    --server.enableXsrfProtection=false \
    --server.headless=true \
    &>/content/streamlit.log &

import time
time.sleep(3)

!cat /content/streamlit.log

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

2026-10-03 09:55:03.959 Uvicorn server started on 0.0.0.0:8501

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.23.235.85:8501

In [23]:
from google.colab import output

dashboard_url = output.eval_js(
    "google.colab.kernel.proxyPort(8501)"
)

print("CII Dashboard URL:")
print(dashboard_url)

CII Dashboard URL:
https://8501-m-s-kkb-use1b2-2isdo80vtbpcs-b.us-east1-2.prod.colab.dev

In [24]:
%%writefile cii_dashboard.py

import streamlit as st
import pandas as pd
import plotly.express as px

# Page configuration
st.set_page_config(
    page_title="Captain Impact Index",
    page_icon="🏏",
    layout="wide"
)

# Load dataset
df = pd.read_csv("CII_Master_Match_Level_Dataset.csv")

# Selected captains
selected_captains = [
    "Sourav Ganguly",
    "Rahul Dravid",
    "MS Dhoni",
    "Virat Kohli",
    "Rohit Sharma"
]

dashboard_df = df[df["Captain"].isin(selected_captains)].copy()

# Title
st.title("🏏 Captain Impact Index (CII)")
st.subheader("Indian Men's ODI Captains — 2005 to 2025")

st.divider()

# KPI calculations
total_matches = len(dashboard_df)
total_captains = len(selected_captains)
total_criteria = 5
analysis_period = "2005–2025"

# KPI cards
col1, col2, col3, col4 = st.columns(4)

with col1:
    st.metric("Total ODI Matches", total_matches)

with col2:
    st.metric("Captains Analyzed", total_captains)

with col3:
    st.metric("CII Criteria", total_criteria)

with col4:
    st.metric("Analysis Period", analysis_period)

Overwriting cii_dashboard.py

In [25]:
!pkill -f "streamlit run cii_dashboard.py" || true

!streamlit run cii_dashboard.py \
    --server.address=0.0.0.0 \
    --server.port=8501 \
    --server.enableCORS=false \
    --server.enableXsrfProtection=false \
    --server.headless=true \
    &>/content/streamlit.log &

import time
time.sleep(3)

print("Streamlit dashboard restarted successfully!")

^C
Streamlit dashboard restarted successfully!

In [26]:
with open("cii_dashboard.py", "a") as f:
    f.write("""

# CII Comparison Chart
st.divider()
st.header("📊 Captain Impact Index Comparison")

cii_summary = (
    dashboard_df[
        [
            "Captain",
            "Win_Score",
            "Pressure_Score",
            "Overseas_Score",
            "Toss_Decision_Score",
            "Home_Performance_Score",
            "CII"
        ]
    ]
    .drop_duplicates("Captain")
    .sort_values("CII", ascending=False)
    .reset_index(drop=True)
)

fig = px.bar(
    cii_summary,
    x="Captain",
    y="CII",
    text="CII",
    title="CII Score by Captain"
)

fig.update_traces(
    texttemplate="%{text:.2f}",
    textposition="outside"
)

fig.update_layout(
    yaxis_range=[0, 100],
    height=500,
    xaxis_title="Captain",
    yaxis_title="CII Score"
)

st.plotly_chart(fig, use_container_width=True)
""")

print("CII Plotly chart added successfully!")

CII Plotly chart added successfully!

In [27]:
!pkill -f "streamlit run cii_dashboard.py" || true

!streamlit run cii_dashboard.py \
    --server.address=0.0.0.0 \
    --server.port=8501 \
    --server.enableCORS=false \
    --server.enableXsrfProtection=false \
    --server.headless=true \
    &>/content/streamlit.log &

import time
time.sleep(3)

print("Dashboard updated successfully!")

^C
Dashboard updated successfully!

In [28]:
with open("cii_dashboard.py", "a") as f:
    f.write("""

# Five Criteria Comparison
st.divider()
st.header("📈 Performance Criteria Comparison")

criteria_long = cii_summary.melt(
    id_vars="Captain",
    value_vars=[
        "Win_Score",
        "Pressure_Score",
        "Overseas_Score",
        "Toss_Decision_Score",
        "Home_Performance_Score"
    ],
    var_name="Criteria",
    value_name="Score"
)

criteria_long["Criteria"] = criteria_long["Criteria"].replace({
    "Win_Score": "Win Score",
    "Pressure_Score": "Pressure Score",
    "Overseas_Score": "Overseas Score",
    "Toss_Decision_Score": "Toss Decision Score",
    "Home_Performance_Score": "Home Performance Score"
})

fig2 = px.bar(
    criteria_long,
    x="Criteria",
    y="Score",
    color="Captain",
    barmode="group",
    text="Score",
    title="Comparison of CII Criteria"
)

fig2.update_traces(
    texttemplate="%{text:.1f}",
    textposition="outside"
)

fig2.update_layout(
    yaxis_range=[0, 100],
    height=600,
    xaxis_title="CII Criteria",
    yaxis_title="Score"
)

st.plotly_chart(fig2, use_container_width=True)
""")

print("Five criteria Plotly chart added successfully!")

Five criteria Plotly chart added successfully!

In [29]:
with open("cii_dashboard.py", "a") as f:
    f.write("""

# Captain Filter
st.divider()
st.header("🎯 Captain Performance Filter")

captain_filter = st.selectbox(
    "Select a Captain",
    selected_captains
)

captain_data = cii_summary[
    cii_summary["Captain"] == captain_filter
]

st.dataframe(
    captain_data,
    use_container_width=True,
    hide_index=True
)
""")

print("Captain filter added successfully!")

Captain filter added successfully!

In [30]:
!pkill -f "streamlit run cii_dashboard.py" || true

!streamlit run cii_dashboard.py \
    --server.address=0.0.0.0 \
    --server.port=8501 \
    --server.enableCORS=false \
    --server.enableXsrfProtection=false \
    --server.headless=true \
    &>/content/streamlit.log &

import time
time.sleep(3)

print("Dashboard restarted successfully!")

^C
Dashboard restarted successfully!

In [31]:
with open("cii_dashboard.py", "a") as f:
    f.write("""

# Home vs Overseas Analysis
st.divider()
st.header("🌍 Home vs Overseas Performance")

location_summary = (
    dashboard_df
    .groupby(["Captain", "Location_Type"])["India_Result"]
    .apply(lambda x: (x == "Win").sum() / ((x == "Win").sum() + (x == "Loss").sum()) * 100
           if ((x == "Win").sum() + (x == "Loss").sum()) > 0 else 0)
    .reset_index(name="Win_Percentage")
)

fig3 = px.bar(
    location_summary,
    x="Captain",
    y="Win_Percentage",
    color="Location_Type",
    barmode="group",
    text="Win_Percentage",
    title="Win Percentage: Home vs Overseas"
)

fig3.update_traces(
    texttemplate="%{text:.1f}%",
    textposition="outside"
)

fig3.update_layout(
    yaxis_range=[0, 100],
    height=550,
    xaxis_title="Captain",
    yaxis_title="Win Percentage (%)"
)

st.plotly_chart(fig3, use_container_width=True)
""")

print("Home vs Overseas Plotly chart added successfully!")

Home vs Overseas Plotly chart added successfully!

In [32]:
!pkill -f "streamlit run cii_dashboard.py" || true

!streamlit run cii_dashboard.py \
    --server.address=0.0.0.0 \
    --server.port=8501 \
    --server.enableCORS=false \
    --server.enableXsrfProtection=false \
    --server.headless=true \
    &>/content/streamlit.log &

import time
time.sleep(3)

print("Dashboard restarted successfully!")

^C
Dashboard restarted successfully!

In [33]:
with open("cii_dashboard.py", "a") as f:
    f.write("""

# Pressure Match Analysis
st.divider()
st.header("🔥 Pressure Match Performance")

pressure_summary = (
    dashboard_df[dashboard_df["Pressure_Match"] == 1]
    .groupby(["Captain", "India_Result"])
    .size()
    .reset_index(name="Matches")
)

fig4 = px.bar(
    pressure_summary,
    x="Captain",
    y="Matches",
    color="India_Result",
    barmode="group",
    text="Matches",
    title="Pressure Match Results by Captain"
)

fig4.update_traces(
    textposition="outside"
)

fig4.update_layout(
    height=550,
    xaxis_title="Captain",
    yaxis_title="Number of Matches"
)

st.plotly_chart(fig4, use_container_width=True)
""")

print("Pressure Match Plotly chart added successfully!")

Pressure Match Plotly chart added successfully!

In [34]:
with open("cii_dashboard.py", "a") as f:
    f.write("""

# Year-wise Match Analysis
st.divider()
st.header("📅 Year-wise Match Analysis")

year_summary = (
    dashboard_df
    .groupby("Year")
    .size()
    .reset_index(name="Matches")
)

fig5 = px.line(
    year_summary,
    x="Year",
    y="Matches",
    markers=True,
    title="Selected Captains' ODI Matches by Year"
)

fig5.update_layout(
    height=500,
    xaxis_title="Year",
    yaxis_title="Number of Matches"
)

st.plotly_chart(fig5, use_container_width=True)
""")

print("Year-wise Plotly chart added successfully!")

Year-wise Plotly chart added successfully!

In [35]:
!pkill -f "streamlit run cii_dashboard.py" || true

!streamlit run cii_dashboard.py \
    --server.address=0.0.0.0 \
    --server.port=8501 \
    --server.enableCORS=false \
    --server.enableXsrfProtection=false \
    --server.headless=true \
    &>/content/streamlit.log &

import time
time.sleep(3)

print("Dashboard restarted successfully!")

^C
Dashboard restarted successfully!

In [36]:
with open("cii_dashboard.py", "r") as f:
    code = f.read()

old_section = '''# Year-wise Match Analysis
st.divider()
st.header("📅 Year-wise Match Analysis")

year_summary = (
    dashboard_df
    .groupby("Year")
    .size()
    .reset_index(name="Matches")
)

fig5 = px.line(
    year_summary,
    x="Year",
    y="Matches",
    markers=True,
    title="Selected Captains' ODI Matches by Year"
)

fig5.update_layout(
    height=500,
    xaxis_title="Year",
    yaxis_title="Number of Matches"
)

st.plotly_chart(fig5, use_container_width=True)
'''

new_section = '''# Year-wise Match Analysis
st.divider()
st.header("📅 Year-wise Match Analysis")

year_summary = (
    dashboard_df
    .groupby(["Year", "Captain"])
    .size()
    .reset_index(name="Matches")
)

fig5 = px.line(
    year_summary,
    x="Year",
    y="Matches",
    color="Captain",
    markers=True,
    title="ODI Matches by Captain and Year"
)

fig5.update_layout(
    height=550,
    xaxis_title="Year",
    yaxis_title="Number of Matches",
    legend_title="Captain"
)

st.plotly_chart(fig5, use_container_width=True)
'''

if old_section in code:
    code = code.replace(old_section, new_section)

with open("cii_dashboard.py", "w") as f:
    f.write(code)

print("Year-wise analysis updated with captain names!")

Year-wise analysis updated with captain names!

In [37]:
!pkill -f "streamlit run cii_dashboard.py" || true

!streamlit run cii_dashboard.py \
    --server.address=0.0.0.0 \
    --server.port=8501 \
    --server.enableCORS=false \
    --server.enableXsrfProtection=false \
    --server.headless=true \
    &>/content/streamlit.log &

import time
time.sleep(3)

print("Dashboard restarted successfully!")

^C
Dashboard restarted successfully!

In [38]:
with open("cii_dashboard.py", "a") as f:
    f.write("""

# CII Methodology
st.divider()
st.header("📘 CII Methodology")

st.write(
    "Captain Impact Index (CII) is a custom performance index developed "
    "for this project to analyze Indian Men's ODI captains from 2005 to 2025."
)

st.markdown("### CII Criteria and Weights")

methodology_data = pd.DataFrame({
    "Criterion": [
        "Win Score",
        "Pressure Score",
        "Overseas Score",
        "Toss Decision Score",
        "Home Performance Score"
    ],
    "Weight": [
        "25%",
        "25%",
        "20%",
        "15%",
        "15%"
    ]
})

st.dataframe(
    methodology_data,
    use_container_width=True,
    hide_index=True
)

st.markdown("### CII Formula")

st.code(
    "CII = 0.25 × Win Score + "
    "0.25 × Pressure Score + "
    "0.20 × Overseas Score + "
    "0.15 × Toss Decision Score + "
    "0.15 × Home Performance Score"
)

st.info(
    "Note: CII is a project-defined composite index and is not an official cricket statistic."
)
""")

print("CII methodology section added successfully!")

CII methodology section added successfully!

In [39]:
!pkill -f "streamlit run cii_dashboard.py" || true

!streamlit run cii_dashboard.py \
    --server.address=0.0.0.0 \
    --server.port=8501 \
    --server.enableCORS=false \
    --server.enableXsrfProtection=false \
    --server.headless=true \
    &>/content/streamlit.log &

import time
time.sleep(3)

print("Dashboard restarted successfully!")

^C
Dashboard restarted successfully!

In [40]:
%%writefile -a cii_dashboard.py

# Key Findings
st.divider()
st.header("🔍 Key Findings")

top_captain = cii_summary.iloc[0]["Captain"]
top_cii = cii_summary.iloc[0]["CII"]

col1, col2, col3 = st.columns(3)

with col1:
    st.metric(
        "Highest CII in Dataset",
        top_captain
    )

with col2:
    st.metric(
        "Highest CII Score",
        f"{top_cii:.2f}"
    )

with col3:
    st.metric(
        "Criteria Used",
        "5"
    )

st.info(
    f"Based on the selected criteria and weighting methodology, "
    f"{top_captain} obtained the highest CII score in this dataset."
)

st.write(
    "The CII score combines Win Score, Pressure Score, Overseas Score, "
    "Toss Decision Score, and Home Performance Score."
)

print("Key Findings section added successfully!")

Appending to cii_dashboard.py

In [41]:
!pkill -f "streamlit run cii_dashboard.py" || true

!streamlit run cii_dashboard.py \
    --server.address=0.0.0.0 \
    --server.port=8501 \
    --server.enableCORS=false \
    --server.enableXsrfProtection=false \
    --server.headless=true \
    &>/content/streamlit.log &

import time
time.sleep(3)

print("Dashboard restarted successfully!")

^C
Dashboard restarted successfully!

In [42]:
%%writefile -a cii_dashboard.py

# Final CII Summary Table
st.divider()
st.header("📋 Final CII Summary")

final_table = cii_summary.copy()

final_table = final_table.rename(columns={
    "Captain": "Captain",
    "Win_Score": "Win Score",
    "Pressure_Score": "Pressure Score",
    "Overseas_Score": "Overseas Score",
    "Toss_Decision_Score": "Toss Decision Score",
    "Home_Performance_Score": "Home Performance Score",
    "CII": "Final CII"
})

st.dataframe(
    final_table,
    use_container_width=True,
    hide_index=True
)

print("Final CII Summary section added successfully!")

Appending to cii_dashboard.py

In [43]:
!pkill -f "streamlit run cii_dashboard.py" || true

!streamlit run cii_dashboard.py \
    --server.address=0.0.0.0 \
    --server.port=8501 \
    --server.enableCORS=false \
    --server.enableXsrfProtection=false \
    --server.headless=true \
    &>/content/streamlit.log &

import time
time.sleep(3)

print("Dashboard restarted successfully!")

^C
Dashboard restarted successfully!

In [44]:
%%writefile -a cii_dashboard.py

# Project Credits
st.divider()
st.markdown(
    """
    <div style="text-align:center; padding:15px;">
        <h4>🏏 Captain Impact Index (CII)</h4>
        <p>Indian Men's ODI Captains — 2005 to 2025</p>
        <p><b>Technologies Used:</b> Python • Pandas • Plotly • Streamlit</p>
        <p>CII is a project-defined composite performance index.</p>
    </div>
    """,
    unsafe_allow_html=True
)

print("Project footer added successfully!")

Appending to cii_dashboard.py

In [45]:
!pkill -f "streamlit run cii_dashboard.py" || true

!streamlit run cii_dashboard.py \
    --server.address=0.0.0.0 \
    --server.port=8501 \
    --server.enableCORS=false \
    --server.enableXsrfProtection=false \
    --server.headless=true \
    &>/content/streamlit.log &

import time
time.sleep(3)

print("Final dashboard restarted successfully!")

^C
Final dashboard restarted successfully!

In [46]:
# Update Team Details

with open("cii_dashboard.py", "r") as f:
    code = f.read()

old_team = '''<p><b>Team Leader:</b> R. Bharath — BETN1AI25203</p>
        <p>U. Naga Lokesh — BETN1AI25217</p>
        <p>M. Amar Deepika — BETN1AI25185</p>'''

new_team = '''<p><b>Team Leader:</b> R. Bharath — BETN1AI25203</p>
        <p><b>Team Member:</b> U. Naga Lokesh — BETN1AI25217</p>
        <p><b>Team Member:</b> M. Amar Deepika — BETN1AI25185</p>'''

if old_team in code:
    code = code.replace(old_team, new_team)
else:
    print("Existing team section not found. Please check the footer.")

with open("cii_dashboard.py", "w") as f:
    f.write(code)

print("All three team members updated successfully!")

Existing team section not found. Please check the footer.
All three team members updated successfully!

In [47]:
# Add Team Details at the Top of the Dashboard

with open("cii_dashboard.py", "r") as f:
    code = f.read()

marker = 'st.subheader("Indian Men\'s ODI Captains — 2005 to 2025")'

team_section = '''
st.markdown(
    """
    <div style="text-align:center; padding:10px;">
        <p><b>Team Leader:</b> R. Bharath — BETN1AI25203</p>
        <p><b>Team Member:</b> U. Naga Lokesh — BETN1AI25217</p>
        <p><b>Team Member:</b> M. Amar Deepika — BETN1AI25185</p>
    </div>
    """,
    unsafe_allow_html=True
)
'''

if team_section not in code:
    code = code.replace(
        marker,
        marker + "\n" + team_section
    )

with open("cii_dashboard.py", "w") as f:
    f.write(code)

print("Team details added to the top of the dashboard!")

Team details added to the top of the dashboard!

In [48]:
!pkill -f "streamlit run cii_dashboard.py" || true

!streamlit run cii_dashboard.py \
    --server.address=0.0.0.0 \
    --server.port=8501 \
    --server.enableCORS=false \
    --server.enableXsrfProtection=false \
    --server.headless=true \
    &>/content/streamlit.log &

import time
time.sleep(3)

print("Dashboard restarted successfully!")

^C
Dashboard restarted successfully!